default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV["HADNU_DB_HOST"] %>
  port: <%= ENV["HADNU_DB_PORT"] %>
  database: <%= ENV["HADNU_DB_NAME"] %>
  username: <%= ENV["HADNU_DB_USER_NAME"] %>
  password: <%= ENV["HADNU_DB_USER_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
  database: hadnu_test

production:
  <<: *default
